# Application Indicateurs de garde

# Récupération des variables

In [1]:
import pandas as pd
import getpass
import datetime
import numpy as np

In [2]:
# utilisateurs
username = getpass.getuser()

In [3]:
df_planning=pd.read_csv('C:/Users/'+username+'/Imadis Téléradiologie/INTRANET - IMADIS/QUALITE/7- RHM/15 - DMA/GitHub/data/BDD.csv')

In [4]:
df_planning = df_planning[df_planning['Source'].isin(['PDS', 'CDS'])]
df_planning = df_planning[df_planning['Formation'].isna()]
df_planning.sample(5)

,Source,Nom_Prenom,Date,Heure_Début,Heure_Fin,Horaire,Date_Heure_Début,Date_Heure_Fin,Associé,mail,Site,Jour/Nuit,Chef,Formation,Durée
33964,PDS,MARCHI BAPTISTE,21/12/2022,20:00:00,08:00:00,20:00:00 - 08:00:00,2022-12-21 20:00:00,2022-12-22 08:00:00,Interne,b.marchi@imadis.fr,Marseille,Nuit,NaN,NaN,12.0
8929,PDS,NIVET HUBERT,25/01/2021,20:00:00,08:00:00,20:00:00 - 08:00:00,2021-01-25 20:00:00,2021-01-26 08:00:00,Remplaçant,NaN,NaN,NaN,NaN,NaN,12.0
29116,PDS,MUTIN DAVID,07/06/2022,18:00:00,20:00:00,18:00:00 - 20:00:00,2022-07-06 18:00:00,2022-07-06 20:00:00,Interne,d.mutin@imadis.fr,Lyon,Journée,NaN,NaN,2.0
16224,CDS,NGUYEN ANH QUOC,22/12/2021,16:00:00,16:30:00,16:00:00 - 16:30:00,2021-12-22 16:00:00,2021-12-22 16:30:00,Associé,a.nguyen@imadis.fr,St etienne,Journée,NaN,NaN,0.5
28927,PDS,CHAILLOT PIERRE-FLEURY,29/06/2022,19:00:00,20:00:00,19:00:00 - 20:00:00,2022-06-29 19:00:00,2022-06-29 20:00:00,Associé,pf.chaillot@imadis.fr,Lyon,Journée,NaN,NaN,1.0

In [26]:
df_planning.to_csv('df_planning.csv')

In [5]:
df_planning=df_planning.drop(['Source','mail', 'Chef', 'Associé', 'Site', 'Jour/Nuit', 'Nom_Prenom', 'Date', 'Formation', 'Date_Heure_Début', 'Date_Heure_Fin'], axis=1)

In [6]:
df_planning.sample(5)

      Heure_Début Heure_Fin              Horaire  Durée
8937     18:00:00  20:00:00  18:00:00 - 20:00:00    2.0
3964     10:00:00  20:00:00  10:00:00 - 20:00:00   10.0
11643    20:00:00  08:00:00  20:00:00 - 08:00:00   12.0
18442    08:00:00  13:00:00  08:00:00 - 13:00:00    5.0
36647    20:00:00  08:00:00  20:00:00 - 08:00:00   12.0

In [7]:
# Convertir les colonnes de dates en objets DateTime
#df_planning['Heure_Début'] = pd.to_datetime(df_planning['Heure_Début'])
#df_planning['Heure_Fin'] = pd.to_datetime(df_planning['Heure_Fin'])

In [8]:
heures = [str((i+8)%24).zfill(2)+'h-'+str((i+9)%24).zfill(2)+'h' for i in range(24)]

In [9]:
for heure in heures:
    df_planning[heure] = 0

In [10]:
df_planning.sample(4)

,Heure_Début,Heure_Fin,Horaire,Durée,08h-09h,09h-10h,10h-11h,11h-12h,12h-13h,13h-14h,...,22h-23h,23h-00h,00h-01h,01h-02h,02h-03h,03h-04h,04h-05h,05h-06h,06h-07h,07h-08h
8170,20:00:00,08:00:00,20:00:00 - 08:00:00,12.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8213,20:00:00,08:00:00,20:00:00 - 08:00:00,12.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42564,20:00:00,08:00:00,20:00:00 - 08:00:00,12.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5690,08:00:00,20:00:00,08:00:00 - 20:00:00,12.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df_planning.columns[4:].to_list

<bound method IndexOpsMixin.tolist of Index(['08h-09h', '09h-10h', '10h-11h', '11h-12h', '12h-13h', '13h-14h',
       '14h-15h', '15h-16h', '16h-17h', '17h-18h', '18h-19h', '19h-20h',
       '20h-21h', '21h-22h', '22h-23h', '23h-00h', '00h-01h', '01h-02h',
       '02h-03h', '03h-04h', '04h-05h', '05h-06h', '06h-07h', '07h-08h'],
      dtype='object')>

In [24]:
plages_horaires=['08h-09h', '09h-10h', '10h-11h', '11h-12h', '12h-13h', '13h-14h',
       '14h-15h', '15h-16h', '16h-17h', '17h-18h', '18h-19h', '19h-20h',
       '20h-21h', '21h-22h', '22h-23h', '23h-00h', '00h-01h', '01h-02h',
       '02h-03h', '03h-04h', '04h-05h', '05h-06h', '06h-07h', '07h-08h']

for plage in plages_horaires:
    df_planning[plage] = 0

# Vérification des conditions et mise à jour des colonnes
for index, row in df_planning.iterrows():
    heure_debut_str = row['Heure_Début']
    duree = row['Durée']
    heure_debut = int(heure_debut_str.split(':')[0])
    minute_debut = int(heure_debut_str.split(':')[1])

    for plage in plages_horaires:
        plage_debut = int(plage.split('-')[0].replace('h', ''))

        if plage_debut <= heure_debut < plage_debut + duree:
            df_planning.loc[index, plage] = 1

      Heure_Début Heure_Fin              Horaire  Durée  08h-09h  09h-10h  \
730      08:00:00  13:00:00  08:00:00 - 13:00:00    5.0        1        0
731      10:00:00  13:00:00  10:00:00 - 13:00:00    3.0        1        1
732      12:00:00  18:00:00  12:00:00 - 18:00:00    6.0        1        1
733      13:00:00  18:00:00  13:00:00 - 18:00:00    5.0        0        1
734      08:00:00  13:00:00  08:00:00 - 13:00:00    5.0        1        0
...           ...       ...                  ...    ...      ...      ...
43350    20:00:00  08:00:00  20:00:00 - 08:00:00   12.0        0        1
43351    20:00:00  08:00:00  20:00:00 - 08:00:00   12.0        0        1
43352    20:00:00  08:00:00  20:00:00 - 08:00:00   12.0        0        1
43353    20:00:00  08:00:00  20:00:00 - 08:00:00   12.0        0        1
43354    21:00:00  08:00:00  21:00:00 - 08:00:00   11.0        0        0

       10h-11h  11h-12h  12h-13h  13h-14h  14h-15h  15h-16h  16h-17h  17h-18h  \
730          0        0        0        0        0        0        0        0
731          1        0        0        0        0        0        0        0
732          1        1        1        0        0        0        0        0
733          1        1        1        1        0        0        0        0
734          0        0        0        0        0        0        0        0
...        ...      ...      ...      ...      ...      ...      ...      ...
43350        1        1        1        1        1        1        1        1
43351        1        1        1        1        1        1        1        1
43352        1        1        1        1        1        1        1        1
43353        1        1        1        1        1        1        1        1
43354        0        1        1        1        1        1        1        1

       18h-19h  19h-20h  20h-21h  21h-22h  22h-23h  23h-00h  00h-01h  01h-02h  \
730          0        0        0        0        0        0        0        0
731          0        0        0        0        0        0        0        0
732          0        0        0        0        0        0        0        0
733          0        0        0        0        0        0        0        0
734          0        0        0        0        0        0        0        0
...        ...      ...      ...      ...      ...      ...      ...      ...
43350        1        1        1        0        0        0        0        0
43351        1        1        1        0        0        0        0        0
43352        1        1        1        0        0        0        0        0
43353        1        1        1        0        0        0        0        0
43354        1        1        1        1        0        0        0        0

       02h-03h  03h-04h  04h-05h  05h-06h  06h-07h  07h-08h
730          0        0        1        1        1        1
731          0        0        0        0        0        0
732          0        0        0        0        0        1
733          0        0        0        0        0        0
734          0        0        1        1        1        1
...        ...      ...      ...      ...      ...      ...
43350        0        0        0        0        0        0
43351        0        0        0        0        0        0
43352        0        0        0        0        0        0
43353        0        0        0        0        0        0
43354        0        0        0        0        0        0

[35325 rows x 28 columns]

In [18]:
'''
marche mais pas après minuit

plages_horaires=['08h-09h', '09h-10h', '10h-11h', '11h-12h', '12h-13h', '13h-14h',
       '14h-15h', '15h-16h', '16h-17h', '17h-18h', '18h-19h', '19h-20h',
       '20h-21h', '21h-22h', '22h-23h', '23h-00h', '00h-01h', '01h-02h',
       '02h-03h', '03h-04h', '04h-05h', '05h-06h', '06h-07h', '07h-08h']

for plage in plages_horaires:
    df_planning[plage] = 0

# Vérification des conditions et mise à jour des colonnes
for index, row in df_planning.iterrows():
    heure_debut = row['Heure_Début']
    duree = row['Durée']

    for plage in plages_horaires:
        plage_debut = int(plage.split('-')[0].replace('h', ''))
        plage_fin = int(plage.split('-')[1].replace('h', ''))
        heure_debut = int(heure_debut.split(':')[0])
        if heure_debut >= plage_debut and heure_debut < plage_fin and duree >= (plage_fin - heure_debut):
            df_planning.loc[index, plage] = 1

idée de base

    if heure_debut == '20:00:00' and duree >= 12:
        df_planning.loc[index, '20h-21h':'07h-08h'] = 1
        '''

In [13]:
'''
marche mais pas après minuit


plages_horaires=['08h-09h', '09h-10h', '10h-11h', '11h-12h', '12h-13h', '13h-14h',
       '14h-15h', '15h-16h', '16h-17h', '17h-18h', '18h-19h', '19h-20h',
       '20h-21h', '21h-22h', '22h-23h', '23h-00h', '00h-01h', '01h-02h',
       '02h-03h', '03h-04h', '04h-05h', '05h-06h', '06h-07h', '07h-08h']

for plage in plages_horaires:
    df_planning[plage] = 0

# Vérification des conditions et mise à jour des colonnes
for index, row in df_planning.iterrows():
    heure_debut_str = row['Heure_Début']
    duree = row['Durée']
    heure_debut = int(heure_debut_str.split(':')[0])
    minute_debut = int(heure_debut_str.split(':')[1])
    heure_fin = heure_debut + duree if heure_debut + duree < 24 else heure_debut + duree - 24

    for plage in plages_horaires:
        plage_debut = int(plage.split('-')[0].replace('h', ''))
        plage_fin = int(plage.split('-')[1].replace('h', ''))

        if heure_debut < plage_fin and heure_fin > plage_debut:
            df_planning.loc[index, plage] = 1
            '''

"\nplages_horaires=['08h-09h', '09h-10h', '10h-11h', '11h-12h', '12h-13h', '13h-14h',\n       '14h-15h', '15h-16h', '16h-17h', '17h-18h', '18h-19h', '19h-20h',\n       '20h-21h', '21h-22h', '22h-23h', '23h-00h', '00h-01h', '01h-02h',\n       '02h-03h', '03h-04h', '04h-05h', '05h-06h', '06h-07h', '07h-08h']\n\nfor plage in plages_horaires:\n    df_planning[plage] = 0\n\n# Vérification des conditions et mise à jour des colonnes\nfor index, row in df_planning.iterrows():\n    heure_debut_str = row['Heure_Début']\n    duree = row['Durée']\n    heure_debut = int(heure_debut_str.split(':')[0])\n    minute_debut = int(heure_debut_str.split(':')[1])\n    heure_fin = heure_debut + duree if heure_debut + duree < 24 else heure_debut + duree - 24\n\n    for plage in plages_horaires:\n        plage_debut = int(plage.split('-')[0].replace('h', ''))\n        plage_fin = int(plage.split('-')[1].replace('h', ''))\n\n        if heure_debut < plage_fin and heure_fin > plage_debut:\n            df_planning.loc[index, plage] = 1\n            "

In [25]:
pd.set_option('display.max_columns', None)
df_planning.sample(4)

,Heure_Début,Heure_Fin,Horaire,Durée,08h-09h,09h-10h,10h-11h,11h-12h,12h-13h,13h-14h,14h-15h,15h-16h,16h-17h,17h-18h,18h-19h,19h-20h,20h-21h,21h-22h,22h-23h,23h-00h,00h-01h,01h-02h,02h-03h,03h-04h,04h-05h,05h-06h,06h-07h,07h-08h
42361,08:00:00,19:00:00,08:00:00 - 19:00:00,11.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1
1832,08:00:00,13:00:00,08:00:00 - 13:00:00,5.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1
7387,18:00:00,20:00:00,18:00:00 - 20:00:00,2.0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
10773,19:00:00,20:00:00,19:00:00 - 20:00:00,1.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0